appName: League Akari
default: 默认

yes: 是
no: 否
confirm: 确认
na: N/A

summonerPlaceholder: 召唤师 {{index}}
summoner: 召唤师

lanes:
  all: 无
  ALL: 无
  top: 上单
  jungle: 打野
  mid: 中单
  middle: 中单
  bot: 下路
  bottom: 下路
  support: 辅助
  utility: 辅助
  TOP: 上单
  JUNGLE: 打野
  MID: 中单
  MIDDLE: 中单
  BOTTOM: 下路
  BOT: 下路
  SUPPORT: 辅助
  UTILITY: 辅助

positionAssignmentReason:
  FILL_SECONDARY: 副选补位
  FILL_PRIMARY: 主选补位
  PRIMARY: 主选
  SECONDARY: 副选
  AUTOFILL: 系统补位
  AUTOFILL_SHORT: 补

teams:
  all: 所有
  unknown: 未知
  100: 蓝队
  200: 红队
  our: 我方
  their: 敌方
  our-1: 我方 (蓝队)
  our-2: 我方 (红队)
  their-1: 敌方 (蓝队)
  their-2: 敌方 (红队)

queueTypes:
  RANKED_SOLO_5x5: 单双排位
  RANKED_FLEX_SR: 灵活排位
  NORMAL: 匹配模式
  ARAM_UNRANKED_5x5: 极地大乱斗
  CHERRY: 斗魂竞技场
  URF: 无限火力 / 无限乱斗
  RANKED_FLEX_TT: 灵活排位 3v3
  NORMAL_TFT: 云顶之弈
  RANKED_TFT: 云顶之弈 排位
  RANKED_TFT_TURBO: 云顶之弈 狂暴模式
  RANKED_TFT_DOUBLE_UP: 云顶之弈 双人作战

gameModes:
  CLASSIC: 经典
  ARAM: 极地大乱斗
  URF: 无限火力
  TFT: 云顶之弈

sgpMatchHistoryTags:
  all: 所有模式
  current: 当前模式
  q_420: 单双排位
  q_430: 匹配模式
  q_440: 灵活排位
  q_450: 极地大乱斗
  q_480: 快速模式
  q_490: 快速匹配
  q_900: 无限乱斗
  q_1700: 斗魂竞技场
  q_1900: 无限火力
  q_2300: 神木之门

tiers:
  UNRANKED: 未定级
  IRON: 坚韧黑铁
  BRONZE: 英勇黄铜
  SILVER: 不屈白银
  GOLD: 荣耀黄金
  PLATINUM: 华贵铂金
  EMERALD: 流光翡翠
  DIAMOND: 璀璨钻石
  MASTER: 超凡大师
  GRANDMASTER: 傲世宗师
  CHALLENGER: 最强王者

shortTiers:
  UNRANKED: 无
  IRON: 黑铁
  BRONZE: 黄铜
  SILVER: 白银
  GOLD: 黄金
  PLATINUM: 铂金
  EMERALD: 翡翠
  DIAMOND: 钻石
  MASTER: 大师
  GRANDMASTER: 宗师
  CHALLENGER: 王者

sgpServers:
  TENCENT_HN10: 黑色玫瑰
  TENCENT_HN1: 艾欧尼亚
  TENCENT_NJ100: 联盟一区
  TENCENT_GZ100: 联盟二区
  TENCENT_CQ100: 联盟三区
  TENCENT_TJ100: 联盟四区
  TENCENT_TJ101: 联盟五区
  TENCENT_BGP2: 峡谷之巅
  TENCENT_PBE: 体验服
  TW2: 台湾
  SG2: 新加坡
  PH2: 菲律宾
  VN2: 越南
  PBE: PBE
  EUN: 欧洲东北
  EUW: 欧洲西
  KR: 韩国
  BR1: 巴西
  LA1: 拉丁美洲
  LA2: 拉丁美洲
  OC1: 大洋洲
  TR1: 土耳其
  RU: 俄罗斯
  JP1: 日本
